In [1]:
import pandas as pd

In [2]:
road = pd.read_table("E:\\Capstone Project\\Data\\road\\road.txt",sep = ',',thousands=',')
road

,OBJECTID,FID_taxi_zone_projected_csv,taxi_zone_projected_borough,taxi_zone_projected_location_i,taxi_zone_projected_objectid,taxi_zone_projected_shape_leng,taxi_zone_projected_zone,taxi_zone_projected_com_density,taxi_zone_projected_taxi_commercial,taxi_Commercial_csv_Field1,...,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Length
0,1,102,Queens,101.0,101.0,0.101710,Glen Oaks,0.000000,0.012905,102,...,Gen_use,Surface_ST,Improved,,No,,,No,NaN,203.517389
1,2,197,Queens,203.0,203.0,0.189938,Rosedale,0.017171,0.015844,197,...,Mjr_st,Surface_ST,Part_improved,,,,,,NaN,1685.907300
2,3,102,Queens,101.0,101.0,0.101710,Glen Oaks,0.000000,0.012905,102,...,Gen_use,Surface_ST,Improved,,No,,,No,NaN,207.984527
3,4,260,Bronx,259.0,259.0,0.126750,Woodlawn/Wakefield,0.049747,0.045343,260,...,Gen_use,Surface_ST,Improved,,,,,,NaN,34.316356
4,5,260,Bronx,259.0,259.0,0.126750,Woodlawn/Wakefield,0.049747,0.045343,260,...,Gen_use,Surface_ST,Improved,,,,,,NaN,413.910345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61301,61302,40,Brooklyn,40.0,40.0,0.051851,Carroll Gardens,0.061576,0.061576,40,...,Gen_use,Surface_ST,Improved,,,,,,NaN,3.220965
61302,61303,40,Brooklyn,40.0,40.0,0.051851,Carroll Gardens,0.061576,0.061576,40,...,Gen_use,Surface_ST,Improved,,,,,,NaN,3.220965
61303,61304,40,Brooklyn,40.0,40.0,0.051851,Carroll Gardens,0.061576,0.061576,40,...,Gen_use,Surface_ST,Improved,,,,,,NaN,3.220965
61304,61305,40,Brooklyn,40.0,40.0,0.051851,Carroll Gardens,0.061576,0.061576,40,...,Gen_use,Surface_ST,Improved,,,,,,NaN,3.220965
61305,61306,40,Brooklyn,40.0,40.0,0.051851,Carroll Gardens,0.061576,0.061576,40,...,Gen_use,Surface_ST,Improved,,,,,,NaN,3.220965

In [3]:
road_density = road.groupby('FID_taxi_zone_projected_csv')['Shape_Length'].sum()
road_density

FID_taxi_zone_projected_csv
2       10519.877969
3      180217.527873
4       34168.852806
5      207866.229165
6      180174.891824
           ...
259     90243.990656
260    210162.150935
261    173288.315597
262     23572.929522
263     38103.983015
Name: Shape_Length, Length: 260, dtype: float64

In [4]:
road_density.to_csv(r'E:\\Capstone Project\\Data\\road\\taxi_road.csv',index=True,header = 0, sep=',')